- name: cart server
  hosts: cart
  become: yes
  tasks:
  - name: enable and disable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y;dnf module enable nodejs:18 -y
  
  - name: install nodejs package
    ansible.builtin.package:
     name: nodejs
     state: present

  - name: add user
    ansible.builtin.user:
     name: roboshop
    
  
  - name: create directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: download the package from URL
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/cart.zip
     dest: /tmp
  

  - name: unzip the file
    ansible.builtin.unarchive:
     src: /tmp/cart.zip
     dest: /app
     remote_src: yes
  
  - name: install npm
    ansible.builtin.command: npm install
    args:
     chdir: /app

  - name: copy cart services
    ansible.builtin.copy:
     src: cart.service
     dest: /etc/systemd/system/cart.service
  
  - name: load the daemon serivces
    ansible.builtin.systemd:
     daemon_reload: true
  - name: enable and start the services
    ansible.builtin.systemd:
     name: cart
     enabled: yes
     state: started

    



    

