- name: dispatch server
  hosts: dispatch
  become: yes
  tasks:
  - name: install package
    ansible.builtin.command: dnf install golang -y
  
  - name: add user
    ansible.builtin.user:
     name: roboshop
  
  - name: create directory
    ansible.builtin.file:
     path: /app
     state: directory
  
  - name: download the applicaiton code
    ansible.builtin.get-url:
     url: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
     dest: /tmp
  
  - name: unarchive file
    ansible.builtin.unarchive:
     src: /tmp/dispatch.zip
     dest: /app
  
  - name: download the dependencies
    ansible.builtin.command: go mod init dispatch;go get;go build
    args:
     chdir: /app
  
  - name: copy the file
    ansible.builtin.copy:
     src: dispatch.service
     dest: /etc/systemd/system/dispatch.service
  
  - name: reload daemon
    ansible.builtin.systemd:
     daemon_reload: true
  
  - name: enable and start service
    ansible.builtin.systemd:
     name: dispatch
     enabled: yes
     state: started


