- name: mongodb server
  hosts: mongodb
  become: yes
  tasks:
  - name: copy repo file
    ansible.builtin.copy:
     src: mongodb.repo
     dest: /etc/yum.repos.d/mongodb.repo
  - name: install mongodb
    ansible.builtin.package:
     name: mongodb-org 
     state: present
  - name: enable mongod service
    ansible.builtin.service:
     name: mongod
     enabled: yes
  - name: start mongod services
    ansible.builtin.service:
     name: mongod
     state: started
  - name: replace the hostsip
    ansible.builtin.replace:
     path: /etc/mongod.conf
     regexp: '127.0.0.1'
     replace: '0.0.0.0'
  - name: restart mongod services
    ansible.builtin.service:
     name: mongod
     state: restarted

   