- name: shipping server
  hosts: shipping
  become: yes
  tasks: 
  - name: install maven
    ansible.builtin.command: dnf install maven -y

  - name: add user
    ansible.builtin.user:
     name: roboshop

  - name: create directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: download package
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
     dest: /tmp

  - name: unarchive the file
    ansible.builtin.unarchive:
     src: /tmp/shipping.zip
     dest: /app

  - name: clean package
    ansible.builtin.command: mvn clean package
    args: 
     chdir: /app
  
      