- name: web server
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.command: dnf install nginx -y

  - name: delete the file
    ansible.builtin.file:
     path: /usr/share/nginx/html/*
     state: absent

  - name: download the package
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/web.zip
     dest: /tmp/web.zip
  
  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
     src: /tmp/web.zip
     dest: /usr/share/nginx/html
     remote_src: yes

  - name: copy the roboshop file
    ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf 

  - name: Enable and start the nginx service
    ansible.builtin.systemd:
     name: nginx
     enabled: yes
     state: started
    
  